on:
  push:
    tags:
      - "v*.*.*"
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'
    
    - name: npm install, build, and test
      run: |
        npm install
        npm audit fix
    
    - name: Install lftp
      run: sudo apt-get install lftp

    - name: Run pack:ff
      env:
        APIKEY: ${{secrets.APIKEY}}
        APISECRET: ${{secrets.APISECRET}}
      run: npm run pack:ff
    
    - name: Move addon to FTP server
      env:
        FTP_PASSWORD: ${{secrets.FTPPASSWORD}}
      run: lftp -e "set ftp:ssl-allow no; mirror -R -I *.xpi web-ext-artifacts /site/wwwroot/addon_todo/${{vars.trigramme}}; quit" -u "${{vars.FTPUSERNAME}}","$FTP_PASSWORD" ${{vars.FTPHOST}}